name: Build all

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      enable_v8:
        description: Enable V8
        type: boolean
        required: false
        default: false
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false
      release:
        description: Publish GitHub release
        type: boolean
        required: false
        default: false
      nuget:
        description: Publish on nuget.org
        type: boolean
        required: false
        default: false
      anaconda:
        description: Publish on anaconda.org
        type: boolean
        required: false
        default: false

jobs:
  android_arm:
    name: Android ARM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm
      enable_v8: false

  android_arm_v8:
    name: Android ARM V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: android_arm
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm
      enable_v8: true

  android_arm64:
    name: Android ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm64
      enable_v8: false

  android_arm64_v8:
    name: Android ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: android_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm64
      enable_v8: true

  android_x64:
    name: Android x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x64
      enable_v8: false

  android_x64_v8:
    name: Android x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: android_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x64
      enable_v8: true

  android_x86:
    name: Android x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x86
      enable_v8: false

  android_x86_v8:
    name: Android x86 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: android_x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x86
      enable_v8: true

  ios_arm64:
    name: iOS ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: arm64
      enable_v8: false
      target_environment: device

  ios_arm64_v8:
    name: iOS ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: ios_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: arm64
      enable_v8: true
      target_environment: device

  ios_x64:
    name: iOS x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: x64
      enable_v8: false
      target_environment: simulator

  ios_x64_v8:
    name: iOS x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: ios_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: x64
      enable_v8: true
      target_environment: simulator

  linux_arm:
    name: Linux ARM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm
      enable_v8: false

  linux_arm_v8:
    name: Linux ARM V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_arm
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm
      enable_v8: true

  linux_arm64:
    name: Linux ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm64
      enable_v8: false

  linux_arm64_v8:
    name: Linux ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm64
      enable_v8: true

  linux_x64:
    name: Linux x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64
      enable_v8: false

  linux_x64_v8:
    name: Linux x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64
      enable_v8: true

  linux_x86:
    name: Linux x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x86
      enable_v8: false

  linux_x86_v8:
    name: Linux x86 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x86
      enable_v8: true

  mac_arm64:
    name: macOS ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: arm64
      enable_v8: false

  mac_arm64_v8:
    name: macOS ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: mac_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: arm64
      enable_v8: true

  mac_x64:
    name: macOS x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: x64
      enable_v8: false

  mac_x64_v8:
    name: macOS x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: mac_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: x64
      enable_v8: true

  win_arm64:
    name: Windows ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: arm64
      enable_v8: false

  win_arm64_v8:
    name: Windows ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: win_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: arm64
      enable_v8: true

  win_x64:
    name: Windows x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x64
      enable_v8: false

  win_x64_v8:
    name: Windows x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: win_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x64
      enable_v8: true

  win_x86:
    name: Windows x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x86
      enable_v8: false

  win_x86_v8:
    name: Windows x86 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: win_x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x86
      enable_v8: true

  wasm:
    name: WASM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: wasm
      target_cpu: wasm
      enable_v8: false

  mac_univ:
    name: macOS univ
    needs:
      - mac_arm64
      - mac_x64
    uses: ./.github/workflows/mac-univ.yml
    with:
      artifact_x64: ${{ needs.mac_x64.outputs.artifact }}
      artifact_arm64: ${{ needs.mac_arm64.outputs.artifact }}

  mac_univ_v8:
    name: macOS univ V8
    needs:
      - mac_arm64_v8
      - mac_x64_v8
    uses: ./.github/workflows/mac-univ.yml
    with:
      artifact_x64: ${{ needs.mac_x64_v8.outputs.artifact }}
      artifact_arm64: ${{ needs.mac_arm64_v8.outputs.artifact }}
